name: PRL

on:
  push:
    branches:
      - 'packratlist'

jobs:
  scheduled-tzdb-check:
    runs-on: ubuntu-latest

    steps:
    - name: Git setup
      run: |
        git config --global user.email "scolebourne@joda.org"
        git config --global user.name "Stephen Colebourne"
        git config --global advice.detachedHead false
        git config --global init.defaultBranch "main"

    - name: Install lzip
      run: |
        sudo apt-get update -y
        sudo apt-get install -y lzip

    - name: Checkout global-tz
      uses: actions/checkout@v3
      with:
        ref: 'main'
        fetch-depth: 0

    - name: Checkout global-tz
      uses: actions/checkout@v3
      with:
        path: 'global'
        ref: 'global-tz'
        fetch-depth: 0

    - name: Checkout iana-tz
      uses: actions/checkout@v3
      with:
        repository: 'eggert/tz'
        path: 'iana'
        fetch-depth: 0

    - name: Build compatible
      run: |
        cd iana
        make VERSION=prl PACKRATDATA=backzone PACKRATLIST=zone.tab tailored_tarballs
        ls -la

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: iana-prl
        path: iana
        retention-days: 2

#    - uses: actions/setup-java@v2
#      with:
#        distribution: 'temurin'
#        java-version: '17'
#        check-latest: true
#    - name: Execute
#      run: |
#        java GlobalTzMain.java
#    - name: Build
#      run: |
#        cd global
#        ls -la
#        make check VERSION="test" ZONETABLES="zone.tab"
#        make tarballs VERSION="test"
#        ls -la
